### PR TITLE
Refactored to use Browserify for dependency management.

### PR DESCRIPTION
**Pull request by suchanlee**
This required some re-structuring of files, but I kept
most of the code as it was before.

**TODO**
- Dev environment/getting-started documentation
- Build file and template version control

**Notable changes**
- paragraph.js divided into smaller React components
- React components go in directory js/components/
- React components have extension *.react.js
- All build files go to js/build/
- All front-end code moved into static/
  - package.json
  - node_modules/
- js/index.js serves as the application initializer
- Gruntfile.js removed
- compiled css file is called paragraph.css instead of paragraph.min.css

### CODE REVIEW

**Comment by suchanlee** [comment]
This should not be merged yet, until the TODO items are first taken care of. This PR should currently serve as a demonstration of how front-end would be structured with Browserify. Your feedback is greatly appreciated!

Also, some explanation on the new static directory structure:
It now is
<pre>
static/
  package.json
  less/
  css/
  js/
    index.js
    build/
    components/
</pre>

I moved package.json to the static directory because this would allow us to keep all front-end related code here, which I think is better than having it scattered in multiple places.

``package.json`` contains app and dev dependencies, npm scripts, and browserify settings to compile. There are 3 defined scripts: ``js``, ``less``, ``start``, ``build``. ``js`` will watch all js files and compile them to ``paragraph.js`` if any js files change. ``less`` does the same for less files. ``start`` will run both ``js`` and ``less``, which will result in watching for any changes in js or less files. ``build`` will minify and uglify the javascript, and should be run before every release. You can activate any of these scripts by running the command:
<pre>
npm run script_name
</pre>

All compiled js files are placed in ``js/build/``.

``js/components/`` contain all React files and follows the directory conventions for Flux applications. Libraries will go into ``js/lib/``, stores/actions can go into ``js/stores/`` and ``js/actions/`` if we ever transition to Flux.

**Comment by suchanlee** [comment]
You should be able to use test this by performing
1. Go to ``static/``
2. Run ``npm install``
3. Move ``index.html.template`` to ``index.html``
4. Run ``npm start``
5. Start paragraph server

**Comment by eungyu** [comment]
Man, 3am!! What a determination. Thank you.

I get the following error during npm start.

```bash
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'js/build/.paragraph.js'
```

**Comment by suchanlee** [comment]
Haha mustard seed meeting ended at 1am last night and I wasn't too tired :P

Are there more logs? One thing that seems to immediately pop out is that it's looking for ``js/build/.paragraph.js`` instead of ``js/build/paragraph.js``, which is weird since I don't define ``.paragraph.js`` anywhere. But I am not sure if the problem is related to that at all.

**Comment by eungyu** [comment]
Let me give it another try.

**Comment by eungyu** [comment]
Yeah, same error.
This is the error message in its entirety. Do you have any clue?

```bash
eungyu-mac-mini:static eungyu$ npm start

> paragraph@0.1.4 start /Users/eungyu/Code/paragraph/app/static
> npm run js & npm run less


> paragraph@0.1.4 js /Users/eungyu/Code/paragraph/app/static
> watchify -o js/build/paragraph.js -v -d .


> paragraph@0.1.4 less /Users/eungyu/Code/paragraph/app/static
> watch-less -d less -r css -c -e .css

sh: watch-less: command not found

npm ERR! paragraph@0.1.4 less: `watch-less -d less -r css -c -e .css`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the paragraph@0.1.4 less script.
npm ERR! This is most likely a problem with the paragraph package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     watch-less -d less -r css -c -e .css
npm ERR! You can get their info via:
npm ERR!     npm owner ls paragraph
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "less"
npm ERR! cwd /Users/eungyu/Code/paragraph/app/static
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/eungyu/Code/paragraph/app/static/npm-debug.log
npm ERR! not ok code 0

npm ERR! paragraph@0.1.4 start: `npm run js & npm run less`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the paragraph@0.1.4 start script.
npm ERR! This is most likely a problem with the paragraph package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run js & npm run less
npm ERR! You can get their info via:
npm ERR!     npm owner ls paragraph
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/eungyu/Code/paragraph/app/static
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/eungyu/Code/paragraph/app/static/npm-debug.log
npm ERR! not ok code 0
eungyu-mac-mini:static eungyu$ 
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'js/build/.paragraph.js'

npm ERR! paragraph@0.1.4 js: `watchify -o js/build/paragraph.js -v -d .`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the paragraph@0.1.4 js script.
npm ERR! This is most likely a problem with the paragraph package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     watchify -o js/build/paragraph.js -v -d .
npm ERR! You can get their info via:
npm ERR!     npm owner ls paragraph
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "js"
npm ERR! cwd /Users/eungyu/Code/paragraph/app/static
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/eungyu/Code/paragraph/app/static/npm-debug.log
npm ERR! not ok code 0
eungyu-mac-mini:static eungyu$ 
```

**Comment by suchanlee** [comment]
Oh no, I had forgotten to add the dev dependency for ``watch-less`` because it was installed globally for me. I have updated ``package.json`` to include it. Sorry about that!

**Comment by eungyu** [comment]
LGTM

**Pull request merged**
